### ISSUE TITLE
prepareUpdateTrustline with interestRate not specified should not set interests to zero

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/clientlib#150]
Right now if you dont specify the interest rate, the interest will be per default value updated to zero. This is not what a normal user would expect. It should in that case only update the creditlines and leave the interest rates untouched. 

We need to see if this is even possible without changing the contracts.

**Comment by dakingha69** [comment]
I am not really sure how we can cleanly do this without changing/adding some functionality in the backend... One easy option I could think of though would be to change the signature of `prepareUpdate` to
```javascript
function prepareUpdate(
  networkAddress,
  counterpartyAddress,
  creditlineGiven,
  creditlineReceived,
  // change interests to mandatory
  interestRateGiven,
  interestRateReceived,
  options
) {...}
```
So that there are no default values for interests and to **enforce** the developer to handle the interest rates himself.

**Comment by berndbohmeier** [comment]
This would be one option. 
But why can we not query the interest rate from the relay server if they are not given?
Also the method that will not update the interests is there in the contracts, but you said it can not be used because it has the same name as the other updateTrustline method.

**Comment by dakingha69** [comment]
Ah yeah querying the interests from the relay server would be another option.

But I think that using the other "old" `updateTrustline` method would definitely be smoothe
